# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='programs',
            field=models.ManyToManyField(blank=True, to='programs.Program'),
        ),
    ]
