# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 02:38
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, null=True, populate_from='__str__', unique=True, verbose_name='URL'),
        ),
    ]
