# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='image',
            field=models.ImageField(default='', upload_to='staff'),
            preserve_default=False,
        ),
    ]
