# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 03:16
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_trainer_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='about',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
            preserve_default=False,
        ),
    ]
