# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 04:18
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_trainer_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='about',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
