# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 14:18
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='entry',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, null=True, populate_from='title', unique=True, verbose_name='URL'),
        ),
    ]
