# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 17:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160513_1018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-pub_date']},
        ),
        migrations.RemoveField(
            model_name='entry',
            name='date',
        ),
        migrations.AddField(
            model_name='entry',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 13, 17, 13, 21, 99717, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
