# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_auto_20160330_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='youtube_id',
            field=models.CharField(blank=True, help_text='Video ID from YouTube', max_length=100, null=True),
        ),
    ]
